import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";
import Footer from "@/components/footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="bg-black text-white">
      <body className="antialiased min-h-screen flex flex-col">
        {/* The persistent navigation header at the very top */}
        <Navbar />
        
        {/* Main page views swap out inside this growth container element */}
        <div className="flex-grow">
          {children}
        </div>
        
        {/* The copyright text footer resting perfectly at the bottom */}
        <Footer />
      </body>
    </html>
  );
}
